### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by glemaitre** [glemaitre/ramp-engine#1]
TODO:

* [x] The worker should not return the process.
* [x] The worker should implement the status depending of the process launched.
* [x] The scheduler should use the status of the worker to collect the results.
